DROP TABLE IF EXISTS admission;

CREATE TABLE admission ( 
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  admission_date DATE,
  history_number INTEGER,
  full_name VARCHAR,
  given_name VARCHAR,
  surname VARCHAR,
  alias VARCHAR,
  gender VARCHAR,
  for_what_committed VARCHAR,
  for_what_committed_index VARCHAR,
  by_whom_committed VARCHAR,
  age INTEGER,
  whereborn_city VARCHAR,
  whereborn_county VARCHAR,
  whereborn_state VARCHAR,
  whereborn_country VARCHAR,
  parentage VARCHAR,
  parentage_index VARCHAR,
  religion VARCHAR,
  religion_index VARCHAR,
  father_living BOOLEAN,
  mother_living BOOLEAN,
  has_step_father BOOLEAN,
  has_step_mother BOOLEAN,
  father_drinks BOOLEAN,
  mother_drinks BOOLEAN,
  appearance_good BOOLEAN,
  appearance_bad BOOLEAN,
  uses_tobacco BOOLEAN,
  uses_liquour BOOLEAN,
  swears BOOLEAN,
  had_regular_work BOOLEAN,
  can_read BOOLEAN,
  no_of_reader TEXT,
  can_write BOOLEAN,
  played_truant BOOLEAN,
  no_of_times_in_refuge INTEGER,
  complaint_of_father BOOLEAN,
  complaint_of_mother BOOLEAN,
  complaint_of_police BOOLEAN,
  disposal VARCHAR,
  trial_date DATE,
  image_no VARCHAR,
  handle TEXT
);

.mode csv
.import admission.csv admission
